// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from Channel.djinni

#pragma once

#include <functional>

namespace clientsdk {

enum class ChannelErrorId : int {
    USERDISCONNECTED,
    CHANNELTIMEOUT,
    CONNECTIONFAILURE,
    RATELIMITEXCEEDED,
    CHANNELCLOSED,
    CHANNELNOTCONFIRMED,
    INVALIDCONFIRM,
    INVALIDDENY,
};

}  // namespace clientsdk

namespace std {

template <>
struct hash<::clientsdk::ChannelErrorId> {
    size_t operator()(::clientsdk::ChannelErrorId type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
