// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ClientApp.djinni

#pragma once

#include <cstdint>
#include <string>
#include <utility>
#include <vector>

namespace clientsdk {

struct ClientRegistrationData final {
    std::string identity;
    std::string secretKey;
    std::vector<uint8_t> certificate;

    ClientRegistrationData(std::string identity_,
                           std::string secretKey_,
                           std::vector<uint8_t> certificate_)
    : identity(std::move(identity_))
    , secretKey(std::move(secretKey_))
    , certificate(std::move(certificate_))
    {}
};

}  // namespace clientsdk
