// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ClientApp.djinni

#pragma once

#include <string>
#include <utility>

namespace clientsdk {

struct ClientBootstrapNode final {
    std::string mode;
    std::string handshakeKey;
    std::string fingerprint;
    std::string identity;
    std::string address;

    ClientBootstrapNode(std::string mode_,
                        std::string handshakeKey_,
                        std::string fingerprint_,
                        std::string identity_,
                        std::string address_)
    : mode(std::move(mode_))
    , handshakeKey(std::move(handshakeKey_))
    , fingerprint(std::move(fingerprint_))
    , identity(std::move(identity_))
    , address(std::move(address_))
    {}
};

}  // namespace clientsdk
