// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ClientApp.djinni

#pragma once

#include <string>

namespace clientsdk {

enum class ClientRegisterFailureCode;
struct ClientRegistrationData;

class ClientRegisterHandler {
public:
    virtual ~ClientRegisterHandler() {}

    virtual void onRegisterSuccess(const std::string & clientId, const ClientRegistrationData & userData) = 0;

    virtual void onRegisterFailure(const std::string & clientId, ClientRegisterFailureCode code) = 0;
};

}  // namespace clientsdk
