// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ClientApp.djinni

#pragma once

#include <functional>

namespace clientsdk {

enum class ClientLogLevel : int {
    LOGTRACE,
    LOGDEBUG,
    LOGINFO,
    LOGWARNING,
    LOGERROR,
    LOGFATAL,
};

}  // namespace clientsdk

namespace std {

template <>
struct hash<::clientsdk::ClientLogLevel> {
    size_t operator()(::clientsdk::ClientLogLevel type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
