// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ClientApp.djinni

#pragma once

#include <functional>

namespace clientsdk {

enum class ClientChannelSecurity : int {
    SECURE,
    INSECURE,
};

}  // namespace clientsdk

namespace std {

template <>
struct hash<::clientsdk::ClientChannelSecurity> {
    size_t operator()(::clientsdk::ClientChannelSecurity type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
