// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ClientApp.djinni

#pragma once

#include <functional>

namespace clientsdk {

enum class ClientRegisterFailureCode : int {
    SUCCESS,
    CONNECTIONERROR,
    CERTFORMATERROR,
    CERTUNSUPPORTEDVERSION,
    CERTSIGNATUREINVALID,
    CERTINTERNALERROR,
};

}  // namespace clientsdk

namespace std {

template <>
struct hash<::clientsdk::ClientRegisterFailureCode> {
    size_t operator()(::clientsdk::ClientRegisterFailureCode type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
