// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ClientApp.djinni

#pragma once

#include <functional>

namespace clientsdk {

enum class ClientLoginFailureCode : int {
    SUCCESS,
    CONNECTIONERROR,
    NOTREGISTERED,
    CERTIFICATEINVALID,
};

}  // namespace clientsdk

namespace std {

template <>
struct hash<::clientsdk::ClientLoginFailureCode> {
    size_t operator()(::clientsdk::ClientLoginFailureCode type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
