// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ClientApp.djinni

#pragma once

#include <functional>

namespace clientsdk {

enum class ClientAppExitCode : int {
    SUCCESS,
    FATAL,
    NETWORKERROR,
    DISCOVERYFAILURE,
    PRESENCEFAILURE,
    CHANNELFAILURE,
    REGISTRATIONFAILURE,
    LOGINFAILURE,
};

}  // namespace clientsdk

namespace std {

template <>
struct hash<::clientsdk::ClientAppExitCode> {
    size_t operator()(::clientsdk::ClientAppExitCode type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
