// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from VideoStreamer.djinni

#pragma once

#include <functional>

namespace clientsdk {

enum class VideoFrameOrientation : int {
    ROTATE0,
    ROTATE90,
    ROTATE180,
    ROTATE270,
};

}  // namespace clientsdk

namespace std {

template <>
struct hash<::clientsdk::VideoFrameOrientation> {
    size_t operator()(::clientsdk::VideoFrameOrientation type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
