// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ClientApp.djinni

#pragma once

#include "ClientKeyPair.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeClientKeyPair final {
public:
    using CppType = ::clientsdk::ClientKeyPair;
    using JniType = jobject;

    using Boxed = NativeClientKeyPair;

    ~NativeClientKeyPair();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeClientKeyPair();
    friend ::djinni::JniClass<NativeClientKeyPair>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/peerstream/psp/sdk/bridge/ClientKeyPair") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/lang/String;Ljava/lang/String;)V") };
    const jfieldID field_mPublicKey { ::djinni::jniGetFieldID(clazz.get(), "mPublicKey", "Ljava/lang/String;") };
    const jfieldID field_mPrivateKey { ::djinni::jniGetFieldID(clazz.get(), "mPrivateKey", "Ljava/lang/String;") };
};

}  // namespace djinni_generated
