// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from VideoStreamer.djinni

#include "NativeVideoStreamDevice.hpp"  // my header
#include "Marshal.hpp"
#include "NativeVideoStreamCapability.hpp"

namespace djinni_generated {

NativeVideoStreamDevice::NativeVideoStreamDevice() = default;

NativeVideoStreamDevice::~NativeVideoStreamDevice() = default;

auto NativeVideoStreamDevice::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeVideoStreamDevice>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.name)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.identifier)),
                                                           ::djinni::get(::djinni::List<::djinni_generated::NativeVideoStreamCapability>::fromCpp(jniEnv, c.videoCapabilities)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeVideoStreamDevice::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 4);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeVideoStreamDevice>::get();
    return {::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mName)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mIdentifier)),
            ::djinni::List<::djinni_generated::NativeVideoStreamCapability>::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mVideoCapabilities))};
}

}  // namespace djinni_generated
