// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ClientApp.djinni

#include "NativeClientAppConfig.hpp"  // my header
#include "Marshal.hpp"
#include "NativeClientBootstrapNode.hpp"

namespace djinni_generated {

NativeClientAppConfig::NativeClientAppConfig() = default;

NativeClientAppConfig::~NativeClientAppConfig() = default;

auto NativeClientAppConfig::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeClientAppConfig>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.nameSpace)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.subNameSpace)),
                                                           ::djinni::get(::djinni_generated::NativeClientBootstrapNode::fromCpp(jniEnv, c.node)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeClientAppConfig::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 4);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeClientAppConfig>::get();
    return {::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mNameSpace)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mSubNameSpace)),
            ::djinni_generated::NativeClientBootstrapNode::toCpp(jniEnv, jniEnv->GetObjectField(j, data.field_mNode))};
}

}  // namespace djinni_generated
