// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ClientApp.djinni

#include "NativeClientKeyPair.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeClientKeyPair::NativeClientKeyPair() = default;

NativeClientKeyPair::~NativeClientKeyPair() = default;

auto NativeClientKeyPair::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeClientKeyPair>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.publicKey)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.privateKey)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeClientKeyPair::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 3);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeClientKeyPair>::get();
    return {::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mPublicKey)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mPrivateKey))};
}

}  // namespace djinni_generated
