// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ClientApp.djinni

#include "NativeClientNetworkStatus.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeClientNetworkStatus::NativeClientNetworkStatus() = default;

NativeClientNetworkStatus::~NativeClientNetworkStatus() = default;

auto NativeClientNetworkStatus::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeClientNetworkStatus>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::F32::fromCpp(jniEnv, c.networkConnectivity)),
                                                           ::djinni::get(::djinni::I64::fromCpp(jniEnv, c.numEntryNodesConnected)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeClientNetworkStatus::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 3);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeClientNetworkStatus>::get();
    return {::djinni::F32::toCpp(jniEnv, jniEnv->GetFloatField(j, data.field_mNetworkConnectivity)),
            ::djinni::I64::toCpp(jniEnv, jniEnv->GetLongField(j, data.field_mNumEntryNodesConnected))};
}

}  // namespace djinni_generated
