// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from VideoStreamer.djinni

#pragma once

#include "VideoStreamerObserver.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeVideoStreamerObserver final : ::djinni::JniInterface<::clientsdk::VideoStreamerObserver, NativeVideoStreamerObserver> {
public:
    using CppType = std::shared_ptr<::clientsdk::VideoStreamerObserver>;
    using CppOptType = std::shared_ptr<::clientsdk::VideoStreamerObserver>;
    using JniType = jobject;

    using Boxed = NativeVideoStreamerObserver;

    ~NativeVideoStreamerObserver();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeVideoStreamerObserver>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeVideoStreamerObserver>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeVideoStreamerObserver();
    friend ::djinni::JniClass<NativeVideoStreamerObserver>;
    friend ::djinni::JniInterface<::clientsdk::VideoStreamerObserver, NativeVideoStreamerObserver>;

    class JavaProxy final : ::djinni::JavaProxyHandle<JavaProxy>, public ::clientsdk::VideoStreamerObserver
    {
    public:
        JavaProxy(JniType j);
        ~JavaProxy();

        void onVideoStreamDisplayFrameReceived(const std::string & streamId, const std::vector<uint8_t> & buffer, int32_t width, int32_t height, ::clientsdk::VideoFrameOrientation orientation) override;
        void onVideoStreamDestroyed(const std::string & streamId) override;

    private:
        friend ::djinni::JniInterface<::clientsdk::VideoStreamerObserver, ::djinni_generated::NativeVideoStreamerObserver>;
    };

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/peerstream/psp/sdk/bridge/VideoStreamerObserver") };
    const jmethodID method_onVideoStreamDisplayFrameReceived { ::djinni::jniGetMethodID(clazz.get(), "onVideoStreamDisplayFrameReceived", "(Ljava/lang/String;[BIILcom/peerstream/psp/sdk/bridge/VideoFrameOrientation;)V") };
    const jmethodID method_onVideoStreamDestroyed { ::djinni::jniGetMethodID(clazz.get(), "onVideoStreamDestroyed", "(Ljava/lang/String;)V") };
};

}  // namespace djinni_generated
