// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ClientApp.djinni

#include "NativeClientBootstrapNode.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeClientBootstrapNode::NativeClientBootstrapNode() = default;

NativeClientBootstrapNode::~NativeClientBootstrapNode() = default;

auto NativeClientBootstrapNode::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeClientBootstrapNode>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.mode)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.handshakeKey)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.fingerprint)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.identity)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.address)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeClientBootstrapNode::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 6);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeClientBootstrapNode>::get();
    return {::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mMode)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mHandshakeKey)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mFingerprint)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mIdentity)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mAddress))};
}

}  // namespace djinni_generated
