// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from VideoStreamer.djinni

#include "NativeVideoStreamBroadcastRetrieverHandler.hpp"  // my header
#include "Marshal.hpp"

namespace djinni_generated {

NativeVideoStreamBroadcastRetrieverHandler::NativeVideoStreamBroadcastRetrieverHandler() : ::djinni::JniInterface<::clientsdk::VideoStreamBroadcastRetrieverHandler, NativeVideoStreamBroadcastRetrieverHandler>() {}

NativeVideoStreamBroadcastRetrieverHandler::~NativeVideoStreamBroadcastRetrieverHandler() = default;

NativeVideoStreamBroadcastRetrieverHandler::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeVideoStreamBroadcastRetrieverHandler::JavaProxy::~JavaProxy() = default;

void NativeVideoStreamBroadcastRetrieverHandler::JavaProxy::onRetrieveBroadcastStreamId(const std::optional<std::string> & c_streamId) {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeVideoStreamBroadcastRetrieverHandler>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_onRetrieveBroadcastStreamId,
                           ::djinni::get(::djinni::Optional<std::optional, ::djinni::String>::fromCpp(jniEnv, c_streamId)));
    ::djinni::jniExceptionCheck(jniEnv);
}

}  // namespace djinni_generated
