// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ClientApp.djinni

#pragma once

#include "ClientRegisterFailureCode.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeClientRegisterFailureCode final : ::djinni::JniEnum {
public:
    using CppType = ::clientsdk::ClientRegisterFailureCode;
    using JniType = jobject;

    using Boxed = NativeClientRegisterFailureCode;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeClientRegisterFailureCode>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeClientRegisterFailureCode>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeClientRegisterFailureCode() : JniEnum("com/peerstream/psp/sdk/bridge/ClientRegisterFailureCode") {}
    friend ::djinni::JniClass<NativeClientRegisterFailureCode>;
};

}  // namespace djinni_generated
