// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from VideoStreamer.djinni

#pragma once

#include "VideoFrameOrientation.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeVideoFrameOrientation final : ::djinni::JniEnum {
public:
    using CppType = ::clientsdk::VideoFrameOrientation;
    using JniType = jobject;

    using Boxed = NativeVideoFrameOrientation;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeVideoFrameOrientation>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeVideoFrameOrientation>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeVideoFrameOrientation() : JniEnum("com/peerstream/psp/sdk/bridge/VideoFrameOrientation") {}
    friend ::djinni::JniClass<NativeVideoFrameOrientation>;
};

}  // namespace djinni_generated
