// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ClientApp.djinni

#pragma once

#include <string>

namespace clientsdk {

enum class ClientAppExitCode;
struct ClientNetworkStatus;

class ClientAppObserver {
public:
    virtual ~ClientAppObserver() {}

    virtual void onApplicationReady(const std::string & clientId) = 0;

    virtual void onApplicationExit(ClientAppExitCode code) = 0;

    virtual void onChannelRequested(const std::string & clientId, const std::string & userId) = 0;

    virtual void onNetworkStatus(const std::string & clientId, const ClientNetworkStatus & status) = 0;

    virtual void onUserPresenceChange(const std::string & clientId, const std::string & userId, bool isActive) = 0;
};

}  // namespace clientsdk
