// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ClientApp.djinni

#pragma once

#include "ClientBootstrapNode.hpp"
#include <string>
#include <utility>

namespace clientsdk {

struct ClientAppConfig final {
    std::string nameSpace;
    std::string subNameSpace;
    ClientBootstrapNode node;

    ClientAppConfig(std::string nameSpace_,
                    std::string subNameSpace_,
                    ClientBootstrapNode node_)
    : nameSpace(std::move(nameSpace_))
    , subNameSpace(std::move(subNameSpace_))
    , node(std::move(node_))
    {}
};

}  // namespace clientsdk
