// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ClientApp.djinni

#pragma once

#include <memory>
#include <string>

namespace clientsdk {

class Channel;
enum class ChannelRequestErrorId;

class ClientChannelHandler {
public:
    virtual ~ClientChannelHandler() {}

    virtual void onChannelConfirmed(const std::string & clientId, const std::shared_ptr<Channel> & channel) = 0;

    virtual void onChannelResponseError(const std::string & clientId, ChannelRequestErrorId errorId) = 0;
};

}  // namespace clientsdk
