// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from VideoStreamer.djinni

#pragma once

#include <cstdint>
#include <string>
#include <vector>

namespace clientsdk {

enum class VideoFrameOrientation;

class VideoStreamerObserver {
public:
    virtual ~VideoStreamerObserver() {}

    virtual void onVideoStreamDisplayFrameReceived(const std::string & streamId, const std::vector<uint8_t> & buffer, int32_t width, int32_t height, VideoFrameOrientation orientation) = 0;

    virtual void onVideoStreamDestroyed(const std::string & streamId) = 0;
};

}  // namespace clientsdk
