// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from VideoStreamer.djinni

#pragma once

#include <string>

namespace clientsdk {

enum class VideoStreamErrorId;

class VideoStreamRequestHandler {
public:
    virtual ~VideoStreamRequestHandler() {}

    virtual void onVideoStreamStarted(const std::string & streamId) = 0;

    virtual void onVideoStreamError(VideoStreamErrorId errorId) = 0;
};

}  // namespace clientsdk
