// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from Channel.djinni

package com.peerstream.psp.sdk.bridge;

public abstract class ChannelStreamHandler {
    public abstract void onStreamCreated(String channelId, String streamId);

    public abstract void onStreamError(String channelId, VideoStreamErrorId errorId);
}
