// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from Channel.djinni

package com.peerstream.psp.sdk.bridge;

public enum ChannelErrorId {
    USERDISCONNECTED,
    CHANNELTIMEOUT,
    CONNECTIONFAILURE,
    RATELIMITEXCEEDED,
    CHANNELCLOSED,
    CHANNELNOTCONFIRMED,
    INVALIDCONFIRM,
    INVALIDDENY,
    ;
}
