// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ClientApp.djinni

package com.peerstream.psp.sdk.bridge;

public final class ClientAppConfig {


    /*package*/ final String mNameSpace;

    /*package*/ final String mSubNameSpace;

    /*package*/ final ClientBootstrapNode mNode;

    public ClientAppConfig(
            String nameSpace,
            String subNameSpace,
            ClientBootstrapNode node) {
        this.mNameSpace = nameSpace;
        this.mSubNameSpace = subNameSpace;
        this.mNode = node;
    }

    public String getNameSpace() {
        return mNameSpace;
    }

    public String getSubNameSpace() {
        return mSubNameSpace;
    }

    public ClientBootstrapNode getNode() {
        return mNode;
    }

    @Override
    public String toString() {
        return "ClientAppConfig{" +
                "mNameSpace=" + mNameSpace +
                "," + "mSubNameSpace=" + mSubNameSpace +
                "," + "mNode=" + mNode +
        "}";
    }

}
