// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ClientApp.djinni

package com.peerstream.psp.sdk.bridge;

public abstract class ClientAppObserver {
    public abstract void onApplicationReady(String clientId);

    public abstract void onApplicationExit(ClientAppExitCode code);

    public abstract void onChannelRequested(String clientId, String userId);

    public abstract void onNetworkStatus(String clientId, ClientNetworkStatus status);

    public abstract void onUserPresenceChange(String clientId, String userId, boolean isActive);
}
