// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ClientApp.djinni

package com.peerstream.psp.sdk.bridge;

public final class ClientRegistrationData implements android.os.Parcelable {


    /*package*/ final String mIdentity;

    /*package*/ final String mSecretKey;

    /*package*/ final byte[] mCertificate;

    public ClientRegistrationData(
            String identity,
            String secretKey,
            byte[] certificate) {
        this.mIdentity = identity;
        this.mSecretKey = secretKey;
        this.mCertificate = certificate;
    }

    public String getIdentity() {
        return mIdentity;
    }

    public String getSecretKey() {
        return mSecretKey;
    }

    public byte[] getCertificate() {
        return mCertificate;
    }

    @Override
    public String toString() {
        return "ClientRegistrationData{" +
                "mIdentity=" + mIdentity +
                "," + "mSecretKey=" + mSecretKey +
                "," + "mCertificate=" + mCertificate +
        "}";
    }


    public static final android.os.Parcelable.Creator<ClientRegistrationData> CREATOR
        = new android.os.Parcelable.Creator<ClientRegistrationData>() {
        @Override
        public ClientRegistrationData createFromParcel(android.os.Parcel in) {
            return new ClientRegistrationData(in);
        }

        @Override
        public ClientRegistrationData[] newArray(int size) {
            return new ClientRegistrationData[size];
        }
    };

    public ClientRegistrationData(android.os.Parcel in) {
        this.mIdentity = in.readString();
        this.mSecretKey = in.readString();
        this.mCertificate = in.createByteArray();
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(android.os.Parcel out, int flags) {
        out.writeString(this.mIdentity);
        out.writeString(this.mSecretKey);
        out.writeByteArray(this.mCertificate);
    }

}
