// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from VideoStreamer.djinni

package com.peerstream.psp.sdk.bridge;

import java.util.ArrayList;

public final class VideoStreamDevice {


    /*package*/ final String mName;

    /*package*/ final String mIdentifier;

    /*package*/ final ArrayList<VideoStreamCapability> mVideoCapabilities;

    public VideoStreamDevice(
            String name,
            String identifier,
            ArrayList<VideoStreamCapability> videoCapabilities) {
        this.mName = name;
        this.mIdentifier = identifier;
        this.mVideoCapabilities = videoCapabilities;
    }

    public String getName() {
        return mName;
    }

    public String getIdentifier() {
        return mIdentifier;
    }

    public ArrayList<VideoStreamCapability> getVideoCapabilities() {
        return mVideoCapabilities;
    }

    @Override
    public String toString() {
        return "VideoStreamDevice{" +
                "mName=" + mName +
                "," + "mIdentifier=" + mIdentifier +
                "," + "mVideoCapabilities=" + mVideoCapabilities +
        "}";
    }

}
