// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from VideoStreamer.djinni

package com.peerstream.psp.sdk.bridge;

public final class VideoStreamCapability {


    /*package*/ final int mWidth;

    /*package*/ final int mHeight;

    /*package*/ final int mMaxFPS;

    /*package*/ final boolean mIsInterlaced;

    public VideoStreamCapability(
            int width,
            int height,
            int maxFPS,
            boolean isInterlaced) {
        this.mWidth = width;
        this.mHeight = height;
        this.mMaxFPS = maxFPS;
        this.mIsInterlaced = isInterlaced;
    }

    public int getWidth() {
        return mWidth;
    }

    public int getHeight() {
        return mHeight;
    }

    public int getMaxFPS() {
        return mMaxFPS;
    }

    public boolean getIsInterlaced() {
        return mIsInterlaced;
    }

    @Override
    public String toString() {
        return "VideoStreamCapability{" +
                "mWidth=" + mWidth +
                "," + "mHeight=" + mHeight +
                "," + "mMaxFPS=" + mMaxFPS +
                "," + "mIsInterlaced=" + mIsInterlaced +
        "}";
    }

}
