// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from VideoStreamer.djinni

package com.peerstream.psp.sdk.bridge;

public abstract class VideoStreamBroadcastRetrieverHandler {
    public abstract void onRetrieveBroadcastStreamId(String streamId);
}
