// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from VideoStreamer.djinni

package com.peerstream.psp.sdk.bridge;

public enum VideoFrameOrientation {
    ROTATE0,
    ROTATE90,
    ROTATE180,
    ROTATE270,
    ;
}
