// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ClientApp.djinni

#include "ClientRegisterHandler.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol PSPClientRegisterHandler;

namespace djinni_generated {

class ClientRegisterHandler
{
public:
    using CppType = std::shared_ptr<::clientsdk::ClientRegisterHandler>;
    using CppOptType = std::shared_ptr<::clientsdk::ClientRegisterHandler>;
    using ObjcType = id<PSPClientRegisterHandler>;

    using Boxed = ClientRegisterHandler;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

