// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ClientApp.djinni

#import "PSPClientKeyPair.h"
#include "ClientKeyPair.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class PSPClientKeyPair;

namespace djinni_generated {

struct ClientKeyPair
{
    using CppType = ::clientsdk::ClientKeyPair;
    using ObjcType = PSPClientKeyPair*;

    using Boxed = ClientKeyPair;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
