// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ClientApp.djinni

#include "ClientLoginHandler.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol PSPClientLoginHandler;

namespace djinni_generated {

class ClientLoginHandler
{
public:
    using CppType = std::shared_ptr<::clientsdk::ClientLoginHandler>;
    using CppOptType = std::shared_ptr<::clientsdk::ClientLoginHandler>;
    using ObjcType = id<PSPClientLoginHandler>;

    using Boxed = ClientLoginHandler;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

