// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ClientApp.djinni

#include <clientsdk/ClientApp.hpp>
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class PSPClientApp;

namespace djinni_generated {

class ClientApp
{
public:
    using CppType = std::shared_ptr<::clientsdk::ClientApp>;
    using CppOptType = std::shared_ptr<::clientsdk::ClientApp>;
    using ObjcType = PSPClientApp*;

    using Boxed = ClientApp;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

