// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ClientApp.djinni

#import "PSPClientNetworkStatus.h"
#include "ClientNetworkStatus.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class PSPClientNetworkStatus;

namespace djinni_generated {

struct ClientNetworkStatus
{
    using CppType = ::clientsdk::ClientNetworkStatus;
    using ObjcType = PSPClientNetworkStatus*;

    using Boxed = ClientNetworkStatus;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
