// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ClientApp.djinni

#import "PSPClientBootstrapNode.h"
#include "ClientBootstrapNode.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class PSPClientBootstrapNode;

namespace djinni_generated {

struct ClientBootstrapNode
{
    using CppType = ::clientsdk::ClientBootstrapNode;
    using ObjcType = PSPClientBootstrapNode*;

    using Boxed = ClientBootstrapNode;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
