// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from Channel.djinni

#import "PSPChannelStreamHandler+Private.h"
#import "PSPChannelStreamHandler.h"
#import "DJIMarshal+Private.h"
#import "DJIObjcWrapperCache+Private.h"
#import "PSPVideoStreamErrorId+Private.h"
#include <stdexcept>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace djinni_generated {

class ChannelStreamHandler::ObjcProxy final
: public ::clientsdk::ChannelStreamHandler
, private ::djinni::ObjcProxyBase<ObjcType>
{
    friend class ::djinni_generated::ChannelStreamHandler;
public:
    using ObjcProxyBase::ObjcProxyBase;
    void onStreamCreated(const std::string & c_channelId, const std::string & c_streamId) override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() onStreamCreated:(::djinni::String::fromCpp(c_channelId))
                                                             streamId:(::djinni::String::fromCpp(c_streamId))];
        }
    }
    void onStreamError(const std::string & c_channelId, ::clientsdk::VideoStreamErrorId c_errorId) override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() onStreamError:(::djinni::String::fromCpp(c_channelId))
                                                            errorId:(::djinni::Enum<::clientsdk::VideoStreamErrorId, PSPVideoStreamErrorId>::fromCpp(c_errorId))];
        }
    }
};

}  // namespace djinni_generated

namespace djinni_generated {

auto ChannelStreamHandler::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto ChannelStreamHandler::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return dynamic_cast<ObjcProxy&>(*cpp).djinni_private_get_proxied_objc_object();
}

}  // namespace djinni_generated
