// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ClientApp.djinni

#import "PSPClientRegistrationData.h"
#include "ClientRegistrationData.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class PSPClientRegistrationData;

namespace djinni_generated {

struct ClientRegistrationData
{
    using CppType = ::clientsdk::ClientRegistrationData;
    using ObjcType = PSPClientRegistrationData*;

    using Boxed = ClientRegistrationData;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
