// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ClientApp.djinni

#import "PSPClientAppConfig.h"
#include "ClientAppConfig.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class PSPClientAppConfig;

namespace djinni_generated {

struct ClientAppConfig
{
    using CppType = ::clientsdk::ClientAppConfig;
    using ObjcType = PSPClientAppConfig*;

    using Boxed = ClientAppConfig;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
