// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from VideoStreamer.djinni

#import "PSPVideoStreamDevice.h"
#include "VideoStreamDevice.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class PSPVideoStreamDevice;

namespace djinni_generated {

struct VideoStreamDevice
{
    using CppType = ::clientsdk::VideoStreamDevice;
    using ObjcType = PSPVideoStreamDevice*;

    using Boxed = VideoStreamDevice;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
