// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from VideoStreamer.djinni

#include "VideoStreamBroadcastRetrieverHandler.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol PSPVideoStreamBroadcastRetrieverHandler;

namespace djinni_generated {

class VideoStreamBroadcastRetrieverHandler
{
public:
    using CppType = std::shared_ptr<::clientsdk::VideoStreamBroadcastRetrieverHandler>;
    using CppOptType = std::shared_ptr<::clientsdk::VideoStreamBroadcastRetrieverHandler>;
    using ObjcType = id<PSPVideoStreamBroadcastRetrieverHandler>;

    using Boxed = VideoStreamBroadcastRetrieverHandler;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

