// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from VideoStreamer.djinni

#import "PSPVideoStreamCapability.h"
#include "VideoStreamCapability.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class PSPVideoStreamCapability;

namespace djinni_generated {

struct VideoStreamCapability
{
    using CppType = ::clientsdk::VideoStreamCapability;
    using ObjcType = PSPVideoStreamCapability*;

    using Boxed = VideoStreamCapability;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
