// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from VideoStreamer.djinni

#import "PSPVideoStreamCapability+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto VideoStreamCapability::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I32::toCpp(obj.width),
            ::djinni::I32::toCpp(obj.height),
            ::djinni::I32::toCpp(obj.maxFPS),
            ::djinni::Bool::toCpp(obj.isInterlaced)};
}

auto VideoStreamCapability::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[PSPVideoStreamCapability alloc] initWithWidth:(::djinni::I32::fromCpp(cpp.width))
                                                    height:(::djinni::I32::fromCpp(cpp.height))
                                                    maxFPS:(::djinni::I32::fromCpp(cpp.maxFPS))
                                              isInterlaced:(::djinni::Bool::fromCpp(cpp.isInterlaced))];
}

}  // namespace djinni_generated
