// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from VideoStreamer.djinni

#include "VideoStreamerObserver.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol PSPVideoStreamerObserver;

namespace djinni_generated {

class VideoStreamerObserver
{
public:
    using CppType = std::shared_ptr<::clientsdk::VideoStreamerObserver>;
    using CppOptType = std::shared_ptr<::clientsdk::VideoStreamerObserver>;
    using ObjcType = id<PSPVideoStreamerObserver>;

    using Boxed = VideoStreamerObserver;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

