// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from VideoStreamer.djinni

#include "VideoStreamer.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class PSPVideoStreamer;

namespace djinni_generated {

class VideoStreamer
{
public:
    using CppType = std::shared_ptr<::clientsdk::VideoStreamer>;
    using CppOptType = std::shared_ptr<::clientsdk::VideoStreamer>;
    using ObjcType = PSPVideoStreamer*;

    using Boxed = VideoStreamer;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

