// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ClientApp.djinni

#import <Foundation/Foundation.h>

@interface PSPClientBootstrapNode : NSObject
- (nonnull instancetype)initWithMode:(nonnull NSString *)mode
                        handshakeKey:(nonnull NSString *)handshakeKey
                         fingerprint:(nonnull NSString *)fingerprint
                            identity:(nonnull NSString *)identity
                             address:(nonnull NSString *)address;
+ (nonnull instancetype)ClientBootstrapNodeWithMode:(nonnull NSString *)mode
                                       handshakeKey:(nonnull NSString *)handshakeKey
                                        fingerprint:(nonnull NSString *)fingerprint
                                           identity:(nonnull NSString *)identity
                                            address:(nonnull NSString *)address;

@property (nonatomic, readonly, nonnull) NSString * mode;

@property (nonatomic, readonly, nonnull) NSString * handshakeKey;

@property (nonatomic, readonly, nonnull) NSString * fingerprint;

@property (nonatomic, readonly, nonnull) NSString * identity;

@property (nonatomic, readonly, nonnull) NSString * address;

@end
