// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ClientApp.djinni

#import "PSPClientNetworkStatus.h"


@implementation PSPClientNetworkStatus

- (nonnull instancetype)initWithNetworkConnectivity:(float)networkConnectivity
                             numEntryNodesConnected:(int64_t)numEntryNodesConnected
{
    if (self = [super init]) {
        _networkConnectivity = networkConnectivity;
        _numEntryNodesConnected = numEntryNodesConnected;
    }
    return self;
}

+ (nonnull instancetype)ClientNetworkStatusWithNetworkConnectivity:(float)networkConnectivity
                                            numEntryNodesConnected:(int64_t)numEntryNodesConnected
{
    return [(PSPClientNetworkStatus*)[self alloc] initWithNetworkConnectivity:networkConnectivity
                                                       numEntryNodesConnected:numEntryNodesConnected];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p networkConnectivity:%@ numEntryNodesConnected:%@>", self.class, (void *)self, @(self.networkConnectivity), @(self.numEntryNodesConnected)];
}

@end
