// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ClientApp.djinni

#import "PSPClientAppConfig+Private.h"
#import "DJIMarshal+Private.h"
#import "PSPClientBootstrapNode+Private.h"
#include <cassert>

namespace djinni_generated {

auto ClientAppConfig::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::String::toCpp(obj.nameSpace),
            ::djinni::String::toCpp(obj.subNameSpace),
            ::djinni_generated::ClientBootstrapNode::toCpp(obj.node)};
}

auto ClientAppConfig::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[PSPClientAppConfig alloc] initWithNameSpace:(::djinni::String::fromCpp(cpp.nameSpace))
                                            subNameSpace:(::djinni::String::fromCpp(cpp.subNameSpace))
                                                    node:(::djinni_generated::ClientBootstrapNode::fromCpp(cpp.node))];
}

}  // namespace djinni_generated
