// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from Channel.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, PSPChannelErrorId)
{
    PSPChannelErrorIdUserDisconnected,
    PSPChannelErrorIdChannelTimeout,
    PSPChannelErrorIdConnectionFailure,
    PSPChannelErrorIdRateLimitExceeded,
    PSPChannelErrorIdChannelClosed,
    PSPChannelErrorIdChannelNotConfirmed,
    PSPChannelErrorIdInvalidConfirm,
    PSPChannelErrorIdInvalidDeny,
};
