// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from Channel.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, PSPChannelRequestErrorId)
{
    PSPChannelRequestErrorIdSuccess,
    PSPChannelRequestErrorIdChannelDenied,
    PSPChannelRequestErrorIdChannelTimeout,
    PSPChannelRequestErrorIdUserNotFound,
    PSPChannelRequestErrorIdConnectionFailure,
    PSPChannelRequestErrorIdFailure,
    PSPChannelRequestErrorIdChannelAlreadyExists,
    PSPChannelRequestErrorIdInvalidConfirm,
};
