// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from Channel.djinni

#include "ChannelStreamHandler.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol PSPChannelStreamHandler;

namespace djinni_generated {

class ChannelStreamHandler
{
public:
    using CppType = std::shared_ptr<::clientsdk::ChannelStreamHandler>;
    using CppOptType = std::shared_ptr<::clientsdk::ChannelStreamHandler>;
    using ObjcType = id<PSPChannelStreamHandler>;

    using Boxed = ChannelStreamHandler;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

