// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from Channel.djinni

#include <clientsdk/Channel.hpp>
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class PSPChannel;

namespace djinni_generated {

class Channel
{
public:
    using CppType = std::shared_ptr<::clientsdk::Channel>;
    using CppOptType = std::shared_ptr<::clientsdk::Channel>;
    using ObjcType = PSPChannel*;

    using Boxed = Channel;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

