// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from Channel.djinni

#include "ChannelObserver.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol PSPChannelObserver;

namespace djinni_generated {

class ChannelObserver
{
public:
    using CppType = std::shared_ptr<::clientsdk::ChannelObserver>;
    using CppOptType = std::shared_ptr<::clientsdk::ChannelObserver>;
    using ObjcType = id<PSPChannelObserver>;

    using Boxed = ChannelObserver;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

