// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ClientApp.djinni

#import "PSPClientKeyPair+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto ClientKeyPair::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::String::toCpp(obj.publicKey),
            ::djinni::String::toCpp(obj.privateKey)};
}

auto ClientKeyPair::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[PSPClientKeyPair alloc] initWithPublicKey:(::djinni::String::fromCpp(cpp.publicKey))
                                            privateKey:(::djinni::String::fromCpp(cpp.privateKey))];
}

}  // namespace djinni_generated
