// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ClientApp.djinni

#import <Foundation/Foundation.h>

@interface PSPClientKeyPair : NSObject
- (nonnull instancetype)initWithPublicKey:(nonnull NSString *)publicKey
                               privateKey:(nonnull NSString *)privateKey;
+ (nonnull instancetype)ClientKeyPairWithPublicKey:(nonnull NSString *)publicKey
                                        privateKey:(nonnull NSString *)privateKey;

@property (nonatomic, readonly, nonnull) NSString * publicKey;

@property (nonatomic, readonly, nonnull) NSString * privateKey;

@end
