// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ClientApp.djinni

#import "PSPClientRegisterHandler+Private.h"
#import "PSPClientRegisterHandler.h"
#import "DJIMarshal+Private.h"
#import "DJIObjcWrapperCache+Private.h"
#import "PSPClientRegisterFailureCode+Private.h"
#import "PSPClientRegistrationData+Private.h"
#include <stdexcept>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace djinni_generated {

class ClientRegisterHandler::ObjcProxy final
: public ::clientsdk::ClientRegisterHandler
, private ::djinni::ObjcProxyBase<ObjcType>
{
    friend class ::djinni_generated::ClientRegisterHandler;
public:
    using ObjcProxyBase::ObjcProxyBase;
    void onRegisterSuccess(const std::string & c_clientId, const ::clientsdk::ClientRegistrationData & c_userData) override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() onRegisterSuccess:(::djinni::String::fromCpp(c_clientId))
                                                               userData:(::djinni_generated::ClientRegistrationData::fromCpp(c_userData))];
        }
    }
    void onRegisterFailure(const std::string & c_clientId, ::clientsdk::ClientRegisterFailureCode c_code) override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() onRegisterFailure:(::djinni::String::fromCpp(c_clientId))
                                                                   code:(::djinni::Enum<::clientsdk::ClientRegisterFailureCode, PSPClientRegisterFailureCode>::fromCpp(c_code))];
        }
    }
};

}  // namespace djinni_generated

namespace djinni_generated {

auto ClientRegisterHandler::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto ClientRegisterHandler::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return dynamic_cast<ObjcProxy&>(*cpp).djinni_private_get_proxied_objc_object();
}

}  // namespace djinni_generated
