// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ClientApp.djinni

#import "PSPClientRegisterFailureCode.h"
#import "PSPClientRegistrationData.h"
#import <Foundation/Foundation.h>


@protocol PSPClientRegisterHandler

- (void)onRegisterSuccess:(nonnull NSString *)clientId
                 userData:(nonnull PSPClientRegistrationData *)userData;

- (void)onRegisterFailure:(nonnull NSString *)clientId
                     code:(PSPClientRegisterFailureCode)code;

@end
