// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ClientApp.djinni

#import "PSPClientBootstrapNode+Private.h"
#import "DJIMarshal+Private.h"
#include <cassert>

namespace djinni_generated {

auto ClientBootstrapNode::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::String::toCpp(obj.mode),
            ::djinni::String::toCpp(obj.handshakeKey),
            ::djinni::String::toCpp(obj.fingerprint),
            ::djinni::String::toCpp(obj.identity),
            ::djinni::String::toCpp(obj.address)};
}

auto ClientBootstrapNode::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[PSPClientBootstrapNode alloc] initWithMode:(::djinni::String::fromCpp(cpp.mode))
                                           handshakeKey:(::djinni::String::fromCpp(cpp.handshakeKey))
                                            fingerprint:(::djinni::String::fromCpp(cpp.fingerprint))
                                               identity:(::djinni::String::fromCpp(cpp.identity))
                                                address:(::djinni::String::fromCpp(cpp.address))];
}

}  // namespace djinni_generated
