// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ClientApp.djinni

#import "PSPClientRegistrationData.h"


@implementation PSPClientRegistrationData

- (nonnull instancetype)initWithIdentity:(nonnull NSString *)identity
                               secretKey:(nonnull NSString *)secretKey
                             certificate:(nonnull NSData *)certificate
{
    if (self = [super init]) {
        _identity = [identity copy];
        _secretKey = [secretKey copy];
        _certificate = [certificate copy];
    }
    return self;
}

+ (nonnull instancetype)ClientRegistrationDataWithIdentity:(nonnull NSString *)identity
                                                 secretKey:(nonnull NSString *)secretKey
                                               certificate:(nonnull NSData *)certificate
{
    return [(PSPClientRegistrationData*)[self alloc] initWithIdentity:identity
                                                            secretKey:secretKey
                                                          certificate:certificate];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p identity:%@ secretKey:%@ certificate:%@>", self.class, (void *)self, self.identity, self.secretKey, self.certificate];
}

@end
