// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ClientApp.djinni

#import "PSPClientLoginHandler+Private.h"
#import "PSPClientLoginHandler.h"
#import "DJIMarshal+Private.h"
#import "DJIObjcWrapperCache+Private.h"
#import "PSPClientLoginFailureCode+Private.h"
#import "PSPClientRegistrationData+Private.h"
#include <stdexcept>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace djinni_generated {

class ClientLoginHandler::ObjcProxy final
: public ::clientsdk::ClientLoginHandler
, private ::djinni::ObjcProxyBase<ObjcType>
{
    friend class ::djinni_generated::ClientLoginHandler;
public:
    using ObjcProxyBase::ObjcProxyBase;
    void onLoginSuccess(const std::string & c_clientId, const std::string & c_response, const std::optional<::clientsdk::ClientRegistrationData> & c_data) override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() onLoginSuccess:(::djinni::String::fromCpp(c_clientId))
                                                            response:(::djinni::String::fromCpp(c_response))
                                                                data:(::djinni::Optional<std::optional, ::djinni_generated::ClientRegistrationData>::fromCpp(c_data))];
        }
    }
    void onLoginFailure(const std::string & c_clientId, ::clientsdk::ClientLoginFailureCode c_code) override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() onLoginFailure:(::djinni::String::fromCpp(c_clientId))
                                                                code:(::djinni::Enum<::clientsdk::ClientLoginFailureCode, PSPClientLoginFailureCode>::fromCpp(c_code))];
        }
    }
};

}  // namespace djinni_generated

namespace djinni_generated {

auto ClientLoginHandler::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto ClientLoginHandler::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return dynamic_cast<ObjcProxy&>(*cpp).djinni_private_get_proxied_objc_object();
}

}  // namespace djinni_generated
