// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from VideoStreamer.djinni

#include "VideoStreamRequestHandler.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol PSPVideoStreamRequestHandler;

namespace djinni_generated {

class VideoStreamRequestHandler
{
public:
    using CppType = std::shared_ptr<::clientsdk::VideoStreamRequestHandler>;
    using CppOptType = std::shared_ptr<::clientsdk::VideoStreamRequestHandler>;
    using ObjcType = id<PSPVideoStreamRequestHandler>;

    using Boxed = VideoStreamRequestHandler;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

