// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from VideoStreamer.djinni

#import "PSPVideoStreamCapability.h"
#import "PSPVideoStreamDevice.h"
#import "PSPVideoStreamOptions.h"
#import <Foundation/Foundation.h>
@protocol PSPVideoStreamBroadcastRetrieverHandler;
@protocol PSPVideoStreamRequestHandler;
@protocol PSPVideoStreamerObserver;


@interface PSPVideoStreamer : NSObject

- (void)initialize:(nonnull PSPVideoStreamOptions *)options
          observer:(nullable id<PSPVideoStreamerObserver>)observer;

- (void)startStreaming:(nullable id<PSPVideoStreamRequestHandler>)handler;

- (void)stopStreaming;

- (void)startViewing:(nonnull NSString *)streamId
             handler:(nullable id<PSPVideoStreamRequestHandler>)handler;

- (void)stopViewing:(nonnull NSString *)streamId;

- (void)enableAudioCapture:(BOOL)isEnabled;

- (void)enableVideoCapture:(BOOL)isEnabled;

- (void)setMicrophoneVolume:(int32_t)val;

- (void)setSpeakerVolume:(int32_t)val;

- (void)setAudioInputDevice:(int32_t)index;

- (void)setAudioOutputDevice:(int32_t)index;

- (void)setVideoDevice:(int32_t)index;

- (void)setVideoCapability:(int32_t)index;

- (int32_t)selectedAudioInputDevice;

- (int32_t)selectedAudioOutputDevice;

- (int32_t)selectedVideoDevice;

- (int32_t)selectedVideoCapability;

- (nonnull NSArray<NSString *> *)getAudioInputDevices;

- (nonnull NSArray<NSString *> *)getAudioOutputDevices;

- (nonnull NSArray<PSPVideoStreamDevice *> *)getVideoDevices;

- (nonnull NSArray<PSPVideoStreamCapability *> *)getVideoCapabilities:(int32_t)index;

- (void)retrieveBroadcastStreamId:(nullable id<PSPVideoStreamBroadcastRetrieverHandler>)handler;

@end
