// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from VideoStreamer.djinni

#import "PSPVideoStreamCapability.h"
#import <Foundation/Foundation.h>

@interface PSPVideoStreamDevice : NSObject
- (nonnull instancetype)initWithName:(nonnull NSString *)name
                          identifier:(nonnull NSString *)identifier
                   videoCapabilities:(nonnull NSArray<PSPVideoStreamCapability *> *)videoCapabilities;
+ (nonnull instancetype)VideoStreamDeviceWithName:(nonnull NSString *)name
                                       identifier:(nonnull NSString *)identifier
                                videoCapabilities:(nonnull NSArray<PSPVideoStreamCapability *> *)videoCapabilities;

@property (nonatomic, readonly, nonnull) NSString * name;

@property (nonatomic, readonly, nonnull) NSString * identifier;

@property (nonatomic, readonly, nonnull) NSArray<PSPVideoStreamCapability *> * videoCapabilities;

@end
