// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from VideoStreamer.djinni

#import "PSPVideoStreamBroadcastRetrieverHandler+Private.h"
#import "PSPVideoStreamBroadcastRetrieverHandler.h"
#import "DJIMarshal+Private.h"
#import "DJIObjcWrapperCache+Private.h"
#include <stdexcept>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace djinni_generated {

class VideoStreamBroadcastRetrieverHandler::ObjcProxy final
: public ::clientsdk::VideoStreamBroadcastRetrieverHandler
, private ::djinni::ObjcProxyBase<ObjcType>
{
    friend class ::djinni_generated::VideoStreamBroadcastRetrieverHandler;
public:
    using ObjcProxyBase::ObjcProxyBase;
    void onRetrieveBroadcastStreamId(const std::optional<std::string> & c_streamId) override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() onRetrieveBroadcastStreamId:(::djinni::Optional<std::optional, ::djinni::String>::fromCpp(c_streamId))];
        }
    }
};

}  // namespace djinni_generated

namespace djinni_generated {

auto VideoStreamBroadcastRetrieverHandler::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto VideoStreamBroadcastRetrieverHandler::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return dynamic_cast<ObjcProxy&>(*cpp).djinni_private_get_proxied_objc_object();
}

}  // namespace djinni_generated
