// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from VideoStreamer.djinni

#import <Foundation/Foundation.h>


@protocol PSPVideoStreamBroadcastRetrieverHandler

- (void)onRetrieveBroadcastStreamId:(nullable NSString *)streamId;

@end
