// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from VideoStreamer.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, PSPVideoFrameOrientation)
{
    PSPVideoFrameOrientationRotate0,
    PSPVideoFrameOrientationRotate90,
    PSPVideoFrameOrientationRotate180,
    PSPVideoFrameOrientationRotate270,
};
