// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from VideoStreamer.djinni

#import "PSPVideoFrameOrientation.h"
#import <Foundation/Foundation.h>


@protocol PSPVideoStreamerObserver

- (void)onVideoStreamDisplayFrameReceived:(nonnull NSString *)streamId
                                   buffer:(nonnull NSData *)buffer
                                    width:(int32_t)width
                                   height:(int32_t)height
                              orientation:(PSPVideoFrameOrientation)orientation;

- (void)onVideoStreamDestroyed:(nonnull NSString *)streamId;

@end
