// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from VideoStreamer.djinni

#import "PSPVideoStreamOptions+Private.h"
#import "DJIMarshal+Private.h"
#import "PSPVideoFrameOrientation+Private.h"
#include <cassert>

namespace djinni_generated {

auto VideoStreamOptions::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::Bool::toCpp(obj.audioCaptureEnabled),
            ::djinni::I32::toCpp(obj.initialSpeakerVolume),
            ::djinni::I32::toCpp(obj.initialMicVolume),
            ::djinni::Bool::toCpp(obj.videoCaptureEnabled),
            ::djinni::I32::toCpp(obj.streamingWidth),
            ::djinni::I32::toCpp(obj.streamingHeight),
            ::djinni::Enum<::clientsdk::VideoFrameOrientation, PSPVideoFrameOrientation>::toCpp(obj.orientation)};
}

auto VideoStreamOptions::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[PSPVideoStreamOptions alloc] initWithAudioCaptureEnabled:(::djinni::Bool::fromCpp(cpp.audioCaptureEnabled))
                                                 initialSpeakerVolume:(::djinni::I32::fromCpp(cpp.initialSpeakerVolume))
                                                     initialMicVolume:(::djinni::I32::fromCpp(cpp.initialMicVolume))
                                                  videoCaptureEnabled:(::djinni::Bool::fromCpp(cpp.videoCaptureEnabled))
                                                       streamingWidth:(::djinni::I32::fromCpp(cpp.streamingWidth))
                                                      streamingHeight:(::djinni::I32::fromCpp(cpp.streamingHeight))
                                                          orientation:(::djinni::Enum<::clientsdk::VideoFrameOrientation, PSPVideoFrameOrientation>::fromCpp(cpp.orientation))];
}

}  // namespace djinni_generated
