// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from VideoStreamer.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, PSPVideoStreamErrorId)
{
    PSPVideoStreamErrorIdSuccess,
    PSPVideoStreamErrorIdConnectionFailure,
    PSPVideoStreamErrorIdPartnerDenied,
    PSPVideoStreamErrorIdPartnerRejected,
    PSPVideoStreamErrorIdNotCurrentlyStreaming,
    PSPVideoStreamErrorIdInvalidShare,
    PSPVideoStreamErrorIdInvalidRequest,
    PSPVideoStreamErrorIdChannelNotConfirmed,
    PSPVideoStreamErrorIdStreamNotShared,
};
