// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ClientApp.djinni

#import "PSPClientAppConfig.h"
#import "PSPClientChannelSecurity.h"
#import "PSPClientLogLevel.h"
#import "PSPClientRegistrationData.h"
#import <Foundation/Foundation.h>
@class PSPClientApp;
@class PSPVideoStreamer;
@protocol PSPClientAppObserver;
@protocol PSPClientChannelHandler;
@protocol PSPClientLoginHandler;
@protocol PSPClientRegisterHandler;


@interface PSPClientApp : NSObject

+ (nullable PSPClientApp *)create:(nonnull PSPClientAppConfig *)config
                         observer:(nullable id<PSPClientAppObserver>)observer;

- (void)start;

- (void)stop;

- (void)setMinLogLevel:(PSPClientLogLevel)level;

- (void)registerUser:(nullable id<PSPClientRegisterHandler>)handler;

- (void)login:(nonnull PSPClientRegistrationData *)userData
      handler:(nullable id<PSPClientLoginHandler>)handler;

- (nonnull NSString *)getIdentity;

- (nullable PSPVideoStreamer *)getVideoStreamer;

- (void)createChannel:(nonnull NSString *)userId
             security:(PSPClientChannelSecurity)security
              handler:(nullable id<PSPClientChannelHandler>)handler;

- (void)confirmChannel:(nonnull NSString *)userId
              security:(PSPClientChannelSecurity)security
               handler:(nullable id<PSPClientChannelHandler>)handler;

- (void)denyChannel:(nonnull NSString *)userId;

- (void)registerUserPresenceChange:(nonnull NSString *)userId;

- (void)unregisterUserPresenceChange:(nonnull NSString *)userId;

@end
