// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ClientApp.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, PSPClientChannelSecurity)
{
    PSPClientChannelSecuritySecure,
    PSPClientChannelSecurityInsecure,
};
