// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from Channel.djinni

#import "PSPVideoStreamErrorId.h"
#import <Foundation/Foundation.h>


@protocol PSPChannelStreamHandler

- (void)onStreamCreated:(nonnull NSString *)channelId
               streamId:(nonnull NSString *)streamId;

- (void)onStreamError:(nonnull NSString *)channelId
              errorId:(PSPVideoStreamErrorId)errorId;

@end
