// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from Channel.djinni

#import "PSPChannelErrorId.h"
#import <Foundation/Foundation.h>


@protocol PSPChannelObserver

- (void)onStreamRequested:(nonnull NSString *)channelId;

- (void)onStreamShared:(nonnull NSString *)channelId
              streamId:(nonnull NSString *)streamId;

- (void)onRawReceived:(nonnull NSString *)channelId
                 data:(nonnull NSData *)data;

- (void)onMessageReceived:(nonnull NSString *)channelId
                      msg:(nonnull NSString *)msg;

- (void)onChannelError:(nonnull NSString *)channelId
               errorId:(PSPChannelErrorId)errorId;

@end
