// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ClientApp.djinni

#import "PSPClientBootstrapNode.h"
#import <Foundation/Foundation.h>

@interface PSPClientAppConfig : NSObject
- (nonnull instancetype)initWithNameSpace:(nonnull NSString *)nameSpace
                             subNameSpace:(nonnull NSString *)subNameSpace
                                     node:(nonnull PSPClientBootstrapNode *)node;
+ (nonnull instancetype)ClientAppConfigWithNameSpace:(nonnull NSString *)nameSpace
                                        subNameSpace:(nonnull NSString *)subNameSpace
                                                node:(nonnull PSPClientBootstrapNode *)node;

@property (nonatomic, readonly, nonnull) NSString * nameSpace;

@property (nonatomic, readonly, nonnull) NSString * subNameSpace;

@property (nonatomic, readonly, nonnull) PSPClientBootstrapNode * node;

@end
