// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ClientApp.djinni

#import "PSPClientBootstrapNode.h"


@implementation PSPClientBootstrapNode

- (nonnull instancetype)initWithMode:(nonnull NSString *)mode
                        handshakeKey:(nonnull NSString *)handshakeKey
                         fingerprint:(nonnull NSString *)fingerprint
                            identity:(nonnull NSString *)identity
                             address:(nonnull NSString *)address
{
    if (self = [super init]) {
        _mode = [mode copy];
        _handshakeKey = [handshakeKey copy];
        _fingerprint = [fingerprint copy];
        _identity = [identity copy];
        _address = [address copy];
    }
    return self;
}

+ (nonnull instancetype)ClientBootstrapNodeWithMode:(nonnull NSString *)mode
                                       handshakeKey:(nonnull NSString *)handshakeKey
                                        fingerprint:(nonnull NSString *)fingerprint
                                           identity:(nonnull NSString *)identity
                                            address:(nonnull NSString *)address
{
    return [(PSPClientBootstrapNode*)[self alloc] initWithMode:mode
                                                  handshakeKey:handshakeKey
                                                   fingerprint:fingerprint
                                                      identity:identity
                                                       address:address];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p mode:%@ handshakeKey:%@ fingerprint:%@ identity:%@ address:%@>", self.class, (void *)self, self.mode, self.handshakeKey, self.fingerprint, self.identity, self.address];
}

@end
