// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ClientApp.djinni

#import "PSPClientLoginFailureCode.h"
#import "PSPClientRegistrationData.h"
#import <Foundation/Foundation.h>


@protocol PSPClientLoginHandler

- (void)onLoginSuccess:(nonnull NSString *)clientId
              response:(nonnull NSString *)response
                  data:(nullable PSPClientRegistrationData *)data;

- (void)onLoginFailure:(nonnull NSString *)clientId
                  code:(PSPClientLoginFailureCode)code;

@end
