// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ClientApp.djinni

#import <Foundation/Foundation.h>

@interface PSPClientNetworkStatus : NSObject
- (nonnull instancetype)initWithNetworkConnectivity:(float)networkConnectivity
                             numEntryNodesConnected:(int64_t)numEntryNodesConnected;
+ (nonnull instancetype)ClientNetworkStatusWithNetworkConnectivity:(float)networkConnectivity
                                            numEntryNodesConnected:(int64_t)numEntryNodesConnected;

@property (nonatomic, readonly) float networkConnectivity;

@property (nonatomic, readonly) int64_t numEntryNodesConnected;

@end
