// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ClientApp.djinni

#import <Foundation/Foundation.h>

@interface PSPClientRegistrationData : NSObject
- (nonnull instancetype)initWithIdentity:(nonnull NSString *)identity
                               secretKey:(nonnull NSString *)secretKey
                             certificate:(nonnull NSData *)certificate;
+ (nonnull instancetype)ClientRegistrationDataWithIdentity:(nonnull NSString *)identity
                                                 secretKey:(nonnull NSString *)secretKey
                                               certificate:(nonnull NSData *)certificate;

@property (nonatomic, readonly, nonnull) NSString * identity;

@property (nonatomic, readonly, nonnull) NSString * secretKey;

@property (nonatomic, readonly, nonnull) NSData * certificate;

@end
