// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from ClientApp.djinni

#import "PSPClientAppConfig.h"


@implementation PSPClientAppConfig

- (nonnull instancetype)initWithNameSpace:(nonnull NSString *)nameSpace
                             subNameSpace:(nonnull NSString *)subNameSpace
                                     node:(nonnull PSPClientBootstrapNode *)node
{
    if (self = [super init]) {
        _nameSpace = [nameSpace copy];
        _subNameSpace = [subNameSpace copy];
        _node = node;
    }
    return self;
}

+ (nonnull instancetype)ClientAppConfigWithNameSpace:(nonnull NSString *)nameSpace
                                        subNameSpace:(nonnull NSString *)subNameSpace
                                                node:(nonnull PSPClientBootstrapNode *)node
{
    return [(PSPClientAppConfig*)[self alloc] initWithNameSpace:nameSpace
                                                   subNameSpace:subNameSpace
                                                           node:node];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p nameSpace:%@ subNameSpace:%@ node:%@>", self.class, (void *)self, self.nameSpace, self.subNameSpace, self.node];
}

@end
