// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from VideoStreamer.djinni

#import "PSPVideoStreamCapability.h"


@implementation PSPVideoStreamCapability

- (nonnull instancetype)initWithWidth:(int32_t)width
                               height:(int32_t)height
                               maxFPS:(int32_t)maxFPS
                         isInterlaced:(BOOL)isInterlaced
{
    if (self = [super init]) {
        _width = width;
        _height = height;
        _maxFPS = maxFPS;
        _isInterlaced = isInterlaced;
    }
    return self;
}

+ (nonnull instancetype)VideoStreamCapabilityWithWidth:(int32_t)width
                                                height:(int32_t)height
                                                maxFPS:(int32_t)maxFPS
                                          isInterlaced:(BOOL)isInterlaced
{
    return [(PSPVideoStreamCapability*)[self alloc] initWithWidth:width
                                                           height:height
                                                           maxFPS:maxFPS
                                                     isInterlaced:isInterlaced];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p width:%@ height:%@ maxFPS:%@ isInterlaced:%@>", self.class, (void *)self, @(self.width), @(self.height), @(self.maxFPS), @(self.isInterlaced)];
}

@end
