// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from VideoStreamer.djinni

#import "PSPVideoStreamErrorId.h"
#import <Foundation/Foundation.h>


@protocol PSPVideoStreamRequestHandler

- (void)onVideoStreamStarted:(nonnull NSString *)streamId;

- (void)onVideoStreamError:(PSPVideoStreamErrorId)errorId;

@end
