// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from VideoStreamer.djinni

#import <Foundation/Foundation.h>

@interface PSPVideoStreamCapability : NSObject
- (nonnull instancetype)initWithWidth:(int32_t)width
                               height:(int32_t)height
                               maxFPS:(int32_t)maxFPS
                         isInterlaced:(BOOL)isInterlaced;
+ (nonnull instancetype)VideoStreamCapabilityWithWidth:(int32_t)width
                                                height:(int32_t)height
                                                maxFPS:(int32_t)maxFPS
                                          isInterlaced:(BOOL)isInterlaced;

@property (nonatomic, readonly) int32_t width;

@property (nonatomic, readonly) int32_t height;

@property (nonatomic, readonly) int32_t maxFPS;

@property (nonatomic, readonly) BOOL isInterlaced;

@end
